---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-10.04
- name: ubuntu-12.04
- name: centos-6.5
- name: centos-7.0
- name: fedora-20

provisioner:
    name: chef_solo

suites:
- name: default
  attributes:
    modules:
      modules: [lp]
  run_list:
    - "recipe[modules]"
