name 'modules'
maintainer 'Guilhem Lettron'
maintainer_email 'guilhem@lettron.fr'
license 'Apache-2.0'
description 'Manage modules on linux'
source_url 'https://github.com/redguide/modules'
issues_url 'https://github.com/redguide/modules/issues'

version '0.2.1'
supports 'ubuntu'
supports 'debian'
