name 'modules'
source_url       'https://github.com/sous-chefs/modules'
issues_url       'https://github.com/sous-chefs/modules/issues'
maintainer       'Sous-Chefs'
maintainer_email 'help@sous-chefs.org'
chef_version     '>= 15.3'
license          'Apache-2.0'
description      'Manage modules on linux'
version          '0.2.1'

supports 'ubuntu'
supports 'debian'
