---
name: ci

"on":
  pull_request:
  push:
    branches: [main]

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@2.0.2
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write

  integration:
    needs: lint-unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - almalinux-8
          - almalinux-9
          - amazonlinux-2023
          - centos-7
          - centos-stream-8
          - centos-stream-9
          - debian-10
          - debian-11
          - debian-12
          - fedora-latest
          - opensuse-leap-15
          - rockylinux-8
          - rockylinux-9
          - ubuntu-1804
          - ubuntu-2004
          - ubuntu-2204
        suite:
          - default
